package com.example.wallpaper_app

object Wallpaper {


    var nature = arrayOf(

        R.drawable.nature1,
        R.drawable.nature2,
        R.drawable.nature3,
        R.drawable.nature5,
        R.drawable.nature6,
        R.drawable.nature7,
        R.drawable.nature8,
        R.drawable.nature9,
        R.drawable.nature10,
        R.drawable.nature11,
        R.drawable.nature12,
        R.drawable.nature13,
        R.drawable.nature14,
        R.drawable.nature15,
        R.drawable.nature16,
        R.drawable.nature17,
        R.drawable.nature18,
        R.drawable.nature4,
        R.drawable.nature19,
        R.drawable.nature20,

        )

    var god = arrayOf(

        R.drawable.god1,
        R.drawable.god2,
        R.drawable.god3,
        R.drawable.god4,
        R.drawable.god5,
        R.drawable.god6,
        R.drawable.god7,
        R.drawable.god8,
        R.drawable.god9,
        R.drawable.god10,
        R.drawable.god11,
        R.drawable.god12,
        R.drawable.god13,
        R.drawable.god14,
        R.drawable.god15,
        R.drawable.god16,
        R.drawable.god17,
        R.drawable.god18,
        R.drawable.god19,
        R.drawable.god20,


        )

    var artistic = arrayOf(

        R.drawable.art1,
        R.drawable.art2,
        R.drawable.art3,
        R.drawable.art4,
        R.drawable.art5,
        R.drawable.art6,
        R.drawable.art7,
        R.drawable.art8,
        R.drawable.art9,
        R.drawable.art10,
        R.drawable.art11,
        R.drawable.art12,
        R.drawable.art13,
        R.drawable.art14,
        R.drawable.art15,
        R.drawable.art16,
        R.drawable.art17,
        R.drawable.art18,
        R.drawable.art19,
        R.drawable.art20,

        )

    var Food = arrayOf(

        R.drawable.food1,
        R.drawable.food2,
        R.drawable.food3,
        R.drawable.food4,
        R.drawable.food5,
        R.drawable.food6,
        R.drawable.food18,
        R.drawable.food8,
        R.drawable.food9,
        R.drawable.food10,
        R.drawable.food11,
        R.drawable.food12,
        R.drawable.food13,
        R.drawable.food14,
        R.drawable.food15,
        R.drawable.food16,
        R.drawable.food7,
        R.drawable.food17,
        R.drawable.food19,
        R.drawable.food20

    )

    var Mountain = arrayOf(

        R.drawable.mountain1,
        R.drawable.mountain2,
        R.drawable.mountain3,
        R.drawable.mountain4,
        R.drawable.mountain5,
        R.drawable.mountain6,
        R.drawable.mountain7,
        R.drawable.mountain8,
        R.drawable.mountain9,
        R.drawable.mountain10,
        R.drawable.mountain11,
        R.drawable.mountain12,
        R.drawable.mountain13,
        R.drawable.mountain14,
        R.drawable.mountain15,
        R.drawable.mountain16,
        R.drawable.mountain17,
        R.drawable.mountain18,
        R.drawable.mountain19,
        R.drawable.mountain20

    )

    var cute = arrayOf(

        R.drawable.cute1,
        R.drawable.cute2,
        R.drawable.cute3,
        R.drawable.cute4,
        R.drawable.cute5,
        R.drawable.cute6,
        R.drawable.cute7,
        R.drawable.cute8,
        R.drawable.cute9,
        R.drawable.cute10,
        R.drawable.cute11,
        R.drawable.cute12,
        R.drawable.cute13,
        R.drawable.cute14,
        R.drawable.cute15,
        R.drawable.cute16,
        R.drawable.cute17,
        R.drawable.cute18,
        R.drawable.cute19,
        R.drawable.cute20,

        )

    var night = arrayOf(

        R.drawable.night1,
        R.drawable.night2,
        R.drawable.night3,
        R.drawable.night4,
        R.drawable.night5,
        R.drawable.night6,
        R.drawable.night7,
        R.drawable.night8,
        R.drawable.night9,
        R.drawable.night10,
        R.drawable.night11,
        R.drawable.night12,
        R.drawable.night13,
        R.drawable.night14,
        R.drawable.night15,
        R.drawable.night16,
        R.drawable.night17,
        R.drawable.night18,
        R.drawable.night19,
        R.drawable.night20,

        )

    var Spring = arrayOf(

        R.drawable.spring1,
        R.drawable.spring2,
        R.drawable.spring3,
        R.drawable.spring4,
        R.drawable.spring5,
        R.drawable.spring6,
        R.drawable.spring7,
        R.drawable.spring8,
        R.drawable.spring9,
        R.drawable.spring10,
        R.drawable.spring11,
        R.drawable.spring12,
        R.drawable.spring13,
        R.drawable.spring14,
        R.drawable.spring15,
        R.drawable.spring16,
        R.drawable.spring17,
        R.drawable.spring18,
        R.drawable.spring19,
        R.drawable.spring20,

        )

    var Music = arrayOf(

        R.drawable.music1,
        R.drawable.music2,
        R.drawable.music3,
        R.drawable.music4,
        R.drawable.music5,
        R.drawable.music6,
        R.drawable.music7,
        R.drawable.music8,
        R.drawable.music9,
        R.drawable.music10,
        R.drawable.music11,
        R.drawable.music12,
        R.drawable.music13,
        R.drawable.music14,
        R.drawable.music15,
        R.drawable.music16,
        R.drawable.music17,
        R.drawable.music18,
        R.drawable.music19,
        R.drawable.music20,

        )

    var Girly = arrayOf(

        R.drawable.girly1,
        R.drawable.girly2,
        R.drawable.girly3,
        R.drawable.girly4,
        R.drawable.girly5,
        R.drawable.girly6,
        R.drawable.girly7,
        R.drawable.girly8,
        R.drawable.girly9,
        R.drawable.girly10,
        R.drawable.girly11,
        R.drawable.girly12,
        R.drawable.girly13,
        R.drawable.girly14,
        R.drawable.girly15,
        R.drawable.girly16,
        R.drawable.girly17,
        R.drawable.girly18,
        R.drawable.girly19,
        R.drawable.girly20,

        )

    var Animal = arrayOf(

        R.drawable.animal1,
        R.drawable.animal2,
        R.drawable.animal3,
        R.drawable.animal4,
        R.drawable.animal5,
        R.drawable.animal6,
        R.drawable.animal7,
        R.drawable.animal8,
        R.drawable.animal9,
        R.drawable.animal10,
        R.drawable.animal11,
        R.drawable.animal12,
        R.drawable.animal13,
        R.drawable.animal14,
        R.drawable.animal15,
        R.drawable.animal16,
        R.drawable.animal17,
        R.drawable.animal18,
        R.drawable.animal19,
        R.drawable.animal20,

        )

    var Ocean = arrayOf(

        R.drawable.ocean1,
        R.drawable.ocean2,
        R.drawable.ocean3,
        R.drawable.ocean4,
        R.drawable.ocean5,
        R.drawable.ocean6,
        R.drawable.ocean7,
        R.drawable.ocean8,
        R.drawable.ocean9,
        R.drawable.ocean10,
        R.drawable.ocean11,
        R.drawable.ocean12,
        R.drawable.ocean13,
        R.drawable.ocean14,
        R.drawable.ocean15,
        R.drawable.ocean16,
        R.drawable.ocean17,
        R.drawable.ocean18,
        R.drawable.ocean19,
        R.drawable.ocean20,

        )

    var Birds = arrayOf(

        R.drawable.bird1,
        R.drawable.bird2,
        R.drawable.bird3,
        R.drawable.bird5,
        R.drawable.bird6,
        R.drawable.bird7,
        R.drawable.bird8,
        R.drawable.bird9,
        R.drawable.bird10,
        R.drawable.bird11,
        R.drawable.bird12,
        R.drawable.bird13,
        R.drawable.bird14,
        R.drawable.bird15,
        R.drawable.bird16,
        R.drawable.bird4,
        R.drawable.bird17,
        R.drawable.bird18,
        R.drawable.bird19,
        R.drawable.bird20

    )


    var City = arrayOf(

        R.drawable.city1,
        R.drawable.city2,
        R.drawable.city3,
        R.drawable.city4,
        R.drawable.city5,
        R.drawable.city6,
        R.drawable.city7,
        R.drawable.city8,
        R.drawable.city9,
        R.drawable.city10,
        R.drawable.city11,
        R.drawable.city12,
        R.drawable.city12,
        R.drawable.city13,
        R.drawable.city14,
        R.drawable.city15,
        R.drawable.city16,
        R.drawable.city17,
        R.drawable.city18,
        R.drawable.city20,

        )

    var quotes = arrayOf(

        R.drawable.queto1,
        R.drawable.queto2,
        R.drawable.queto3,
        R.drawable.queto4,
        R.drawable.queto5,
        R.drawable.queto6,
        R.drawable.queto7,
        R.drawable.queto8,
        R.drawable.queto9,
        R.drawable.queto10,
        R.drawable.queto11,
        R.drawable.queto12,
        R.drawable.queto13,
        R.drawable.queto14,
        R.drawable.queto15,
        R.drawable.queto16,
        R.drawable.queto17,
        R.drawable.queto18,
        R.drawable.queto19,
        R.drawable.queto20

    )

    var astronaut = arrayOf(

        R.drawable.astronaut1,
        R.drawable.astronaut2,
        R.drawable.astronaut3,
        R.drawable.astronaut4,
        R.drawable.astronaut5,
        R.drawable.astronaut6,
        R.drawable.astronaut7,
        R.drawable.astronaut8,
        R.drawable.astronaut9,
        R.drawable.astronaut10,
        R.drawable.astronaut11,
        R.drawable.astronaut12,
        R.drawable.astronaut13,
        R.drawable.astronaut14,
        R.drawable.astronaut15,
        R.drawable.astronaut16,
        R.drawable.astronaut17,
        R.drawable.astronaut18,
        R.drawable.astronaut19,
        R.drawable.astronaut20,

        )

    var Love = arrayOf(

        R.drawable.love1,
        R.drawable.love2,
        R.drawable.love3,
        R.drawable.love4,
        R.drawable.love5,
        R.drawable.love6,
        R.drawable.love7,
        R.drawable.love8,
        R.drawable.love9,
        R.drawable.love10,
        R.drawable.love11,
        R.drawable.love12,
        R.drawable.love13,
        R.drawable.love14,
        R.drawable.love15,
        R.drawable.love16,
        R.drawable.love17,
        R.drawable.love18,
        R.drawable.love19,
        R.drawable.love20,

        )

    var Flower = arrayOf(

        R.drawable.flower1,
        R.drawable.flower2,
        R.drawable.flower3,
        R.drawable.flower4,
        R.drawable.flower5,
        R.drawable.flower6,
        R.drawable.flower7,
        R.drawable.flower8,
        R.drawable.flower9,
        R.drawable.flower10,
        R.drawable.flower11,
        R.drawable.flower12,
        R.drawable.flower13,
        R.drawable.flower14,
        R.drawable.flower15,
        R.drawable.flower16,
        R.drawable.flower17,
        R.drawable.flower18,
        R.drawable.flower19,
        R.drawable.flower20,

        )

    var Moon = arrayOf(

        R.drawable.moon1,
        R.drawable.moon2,
        R.drawable.moon3,
        R.drawable.moon4,
        R.drawable.moon5,
        R.drawable.moon6,
        R.drawable.moon7,
        R.drawable.moon8,
        R.drawable.moon9,
        R.drawable.moon10,
        R.drawable.moon11,
        R.drawable.moon12,
        R.drawable.moon13,
        R.drawable.moon14,
        R.drawable.moon15,
        R.drawable.moon16,
        R.drawable.moon17,
        R.drawable.moon18,
        R.drawable.moon19,
        R.drawable.moon20,

        )

    var travel = arrayOf(

        R.drawable.travel1,
        R.drawable.travel2,
        R.drawable.travel3,
        R.drawable.travel4,
        R.drawable.travel5,
        R.drawable.travel6,
        R.drawable.travel7,
        R.drawable.travel8,
        R.drawable.travel9,
        R.drawable.travel10,
        R.drawable.travel11,
        R.drawable.travel12,
        R.drawable.travel13,
        R.drawable.travel14,
        R.drawable.travel15,
        R.drawable.travel16,
        R.drawable.travel17,
        R.drawable.travel18,
        R.drawable.travel19,
        R.drawable.travel20,

        )

    var BlackWhite = arrayOf(

        R.drawable.bw1,
        R.drawable.bw2,
        R.drawable.bw3,
        R.drawable.bw4,
        R.drawable.bw5,
        R.drawable.bw6,
        R.drawable.bw7,
        R.drawable.bw8,
        R.drawable.bw9,
        R.drawable.bw10,
        R.drawable.bw11,
        R.drawable.bw12,
        R.drawable.bw13,
        R.drawable.bw14,
        R.drawable.bw15,
        R.drawable.bw16,
        R.drawable.bw17,
        R.drawable.bw18,
        R.drawable.bw19,
        R.drawable.bw20,

        )

    var Sun = arrayOf(

        R.drawable.sun1,
        R.drawable.sun2,
        R.drawable.sun3,
        R.drawable.sun4,
        R.drawable.sun5,
        R.drawable.sun6,
        R.drawable.sun7,
        R.drawable.sun8,
        R.drawable.sun9,
        R.drawable.sun10,
        R.drawable.sun11,
        R.drawable.sun12,
        R.drawable.sun13,
        R.drawable.sun14,
        R.drawable.sun15,
        R.drawable.sun16,
        R.drawable.sun17,
        R.drawable.sun18,
        R.drawable.sun19,
        R.drawable.sun20,

        )

    var Anime = arrayOf(

        R.drawable.anime1,
        R.drawable.anime2,
        R.drawable.anime3,
        R.drawable.anime4,
        R.drawable.anime5,
        R.drawable.anime6,
        R.drawable.anime7,
        R.drawable.anime8,
        R.drawable.anime9,
        R.drawable.anime10,
        R.drawable.anime11,
        R.drawable.anime12,
        R.drawable.anime13,
        R.drawable.anime14,
        R.drawable.anime15,
        R.drawable.anime16,
        R.drawable.anime17,
        R.drawable.anime18,
        R.drawable.anime19,
        R.drawable.anime20

    )

    var classic = arrayOf(

        R.drawable.classic1,
        R.drawable.classic2,
        R.drawable.classic3,
        R.drawable.classic4,
        R.drawable.classic5,
        R.drawable.classic6,
        R.drawable.classic7,
        R.drawable.classic8,
        R.drawable.classic9,
        R.drawable.classic10,
        R.drawable.classic11,
        R.drawable.classic12,
        R.drawable.classic13,
        R.drawable.classic14,
        R.drawable.classic15,
        R.drawable.classic16,
        R.drawable.classic17,
        R.drawable.classic18,
        R.drawable.classic19,
        R.drawable.classic20

    )

    var allImage = arrayOf(

        R.drawable.spring2,
        R.drawable.food9,
        R.drawable.mountain5,
        R.drawable.astronaut20,
        R.drawable.art10,
        R.drawable.nature6,
        R.drawable.nature7,
        R.drawable.art7,
        R.drawable.art8,
        R.drawable.food10,
        R.drawable.food8,
        R.drawable.art9,
        R.drawable.art3,
        R.drawable.art4,
        R.drawable.art5,
        R.drawable.art6,
        R.drawable.nature1,
        R.drawable.nature2,
        R.drawable.nature3,
        R.drawable.art11,
        R.drawable.art12,
        R.drawable.nature11,
        R.drawable.food11,
        R.drawable.nature12,
        R.drawable.nature13,
        R.drawable.nature14,
        R.drawable.nature15,
        R.drawable.art13,
        R.drawable.art14,
        R.drawable.food3,

        R.drawable.art15,
        R.drawable.nature8,
        R.drawable.nature9,
        R.drawable.nature10,
        R.drawable.art16,
        R.drawable.art17,
        R.drawable.art18,
        R.drawable.art19,
        R.drawable.art20,


        R.drawable.food12,
        R.drawable.food13,
        R.drawable.food14,
        R.drawable.nature16,
        R.drawable.nature17,
        R.drawable.nature18,
        R.drawable.nature19,
        R.drawable.nature20,
        R.drawable.food15,
        R.drawable.art2,

        R.drawable.food16,
        R.drawable.food17,
        R.drawable.food18,
        R.drawable.food19,
        R.drawable.food20,


        R.drawable.mountain6,
        R.drawable.mountain7,
        R.drawable.food2,

        R.drawable.mountain8,
        R.drawable.mountain9,

        R.drawable.food5,
        R.drawable.food6,
        R.drawable.food7,
        R.drawable.nature4,
        R.drawable.nature5,
        R.drawable.food1,

        R.drawable.mountain10,
        R.drawable.night1,
        R.drawable.night2,
        R.drawable.night3,
        R.drawable.night4,
        R.drawable.night5,
        R.drawable.mountain11,
        R.drawable.mountain12,
        R.drawable.mountain13,
        R.drawable.mountain14,
        R.drawable.mountain15,
        R.drawable.mountain16,
        R.drawable.mountain17,
        R.drawable.mountain18,
        R.drawable.art1,

        R.drawable.food4,

        R.drawable.mountain19,
        R.drawable.mountain20,
        R.drawable.cute13,
        R.drawable.cute14,
        R.drawable.cute15,
        R.drawable.cute16,
        R.drawable.mountain1,
        R.drawable.mountain2,
        R.drawable.mountain3,
        R.drawable.mountain4,
        R.drawable.cute17,
        R.drawable.cute18,
        R.drawable.cute19,
        R.drawable.cute20,
        R.drawable.night6,
        R.drawable.girly5,
        R.drawable.girly6,
        R.drawable.spring16,

        R.drawable.girly7,
        R.drawable.girly8,
        R.drawable.girly9,
        R.drawable.girly10,
        R.drawable.girly11,
        R.drawable.night7,
        R.drawable.night8,
        R.drawable.night9,
        R.drawable.bw1,
        R.drawable.bw2,
        R.drawable.bw3,
        R.drawable.bw4,
        R.drawable.night17,
        R.drawable.night18,
        R.drawable.night19,
        R.drawable.night20,
        R.drawable.spring1,
        R.drawable.spring3,
        R.drawable.spring4,
        R.drawable.spring5,
        R.drawable.spring6,
        R.drawable.spring7,
        R.drawable.spring8,
        R.drawable.spring9,
        R.drawable.spring10,
        R.drawable.spring11,
        R.drawable.spring19,
        R.drawable.spring20,
        R.drawable.music1,
        R.drawable.music2,
        R.drawable.music3,
        R.drawable.music4,
        R.drawable.music5,
        R.drawable.music6,
        R.drawable.music7,
        R.drawable.music8,
        R.drawable.music9,
        R.drawable.music10,
        R.drawable.queto6,
        R.drawable.queto7,
        R.drawable.queto8,
        R.drawable.queto9,
        R.drawable.queto10,
        R.drawable.queto11,
        R.drawable.queto12,
        R.drawable.queto13,
        R.drawable.music11,
        R.drawable.music12,
        R.drawable.music13,
        R.drawable.music14,
        R.drawable.music15,
        R.drawable.music16,
        R.drawable.music17,
        R.drawable.music18,
        R.drawable.music19,
        R.drawable.music20,
        R.drawable.girly1,
        R.drawable.girly2,
        R.drawable.girly3,
        R.drawable.girly4,
        R.drawable.girly12,
        R.drawable.girly13,
        R.drawable.cute8,
        R.drawable.cute9,
        R.drawable.cute10,
        R.drawable.cute11,
        R.drawable.cute12,
        R.drawable.girly14,
        R.drawable.girly15,
        R.drawable.girly16,
        R.drawable.girly17,
        R.drawable.girly18,
        R.drawable.girly19,
        R.drawable.girly20,
        R.drawable.animal1,
        R.drawable.animal2,
        R.drawable.animal3,
        R.drawable.animal4,
        R.drawable.animal5,
        R.drawable.animal6,
        R.drawable.animal7,
        R.drawable.animal8,
        R.drawable.animal9,
        R.drawable.animal10,
        R.drawable.animal11,
        R.drawable.animal12,
        R.drawable.animal13,
        R.drawable.animal14,
        R.drawable.animal15,
        R.drawable.animal16,
        R.drawable.animal17,
        R.drawable.animal18,
        R.drawable.animal19,
        R.drawable.animal20,

        R.drawable.ocean1,
        R.drawable.ocean2,
        R.drawable.ocean3,
        R.drawable.ocean4,
        R.drawable.ocean5,
        R.drawable.ocean6,
        R.drawable.ocean7,
        R.drawable.ocean8,
        R.drawable.ocean9,
        R.drawable.ocean10,
        R.drawable.ocean11,
        R.drawable.ocean12,
        R.drawable.ocean13,
        R.drawable.ocean14,
        R.drawable.ocean15,
        R.drawable.ocean16,
        R.drawable.ocean17,
        R.drawable.ocean18,
        R.drawable.ocean19,
        R.drawable.ocean20,

        R.drawable.bird1,
        R.drawable.bird2,
        R.drawable.bird3,
        R.drawable.bird4,
        R.drawable.bird5,
        R.drawable.bird6,
        R.drawable.bird7,
        R.drawable.bird8,
        R.drawable.bird9,
        R.drawable.bird10,
        R.drawable.bird11,
        R.drawable.bird12,
        R.drawable.bird13,
        R.drawable.bird14,
        R.drawable.bird15,
        R.drawable.bird16,
        R.drawable.bird17,
        R.drawable.bird18,
        R.drawable.bird19,
        R.drawable.bird20,

        R.drawable.city1,
        R.drawable.city2,
        R.drawable.city3,
        R.drawable.city4,
        R.drawable.city5,
        R.drawable.city6,
        R.drawable.city7,
        R.drawable.city8,
        R.drawable.city9,
        R.drawable.city10,
        R.drawable.city11,
        R.drawable.city12,
        R.drawable.city12,
        R.drawable.city13,
        R.drawable.city14,
        R.drawable.city15,
        R.drawable.city16,
        R.drawable.city17,
        R.drawable.city18,
        R.drawable.city20,
        R.drawable.queto1,
        R.drawable.cute1,
        R.drawable.cute2,
        R.drawable.cute3,
        R.drawable.cute4,
        R.drawable.cute5,
        R.drawable.cute6,
        R.drawable.cute7,
        R.drawable.queto2,
        R.drawable.queto3,
        R.drawable.queto4,
        R.drawable.queto5,

        R.drawable.queto14,
        R.drawable.queto15,
        R.drawable.queto16,
        R.drawable.queto17,
        R.drawable.queto18,
        R.drawable.queto19,
        R.drawable.queto20,
        R.drawable.spring12,
        R.drawable.spring13,
        R.drawable.spring14,
        R.drawable.spring15,
        R.drawable.spring17,
        R.drawable.spring18,

        R.drawable.astronaut1,
        R.drawable.astronaut2,
        R.drawable.astronaut3,
        R.drawable.astronaut4,
        R.drawable.astronaut5,
        R.drawable.astronaut6,
        R.drawable.astronaut7,
        R.drawable.astronaut8,
        R.drawable.astronaut9,
        R.drawable.astronaut10,
        R.drawable.astronaut11,
        R.drawable.astronaut12,
        R.drawable.astronaut13,
        R.drawable.astronaut14,
        R.drawable.astronaut15,
        R.drawable.astronaut16,
        R.drawable.astronaut17,
        R.drawable.astronaut18,
        R.drawable.astronaut19,
        R.drawable.love1,
        R.drawable.love2,
        R.drawable.love3,
        R.drawable.love4,
        R.drawable.night15,
        R.drawable.night16,
        R.drawable.love6,
        R.drawable.love7,
        R.drawable.love8,
        R.drawable.love15,
        R.drawable.love16,
        R.drawable.love17,
        R.drawable.love18,
        R.drawable.love19,
        R.drawable.love20,
        R.drawable.moon1,
        R.drawable.moon2,
        R.drawable.moon3,
        R.drawable.moon4,
        R.drawable.moon5,
        R.drawable.moon6,
        R.drawable.moon7,
        R.drawable.moon8,
        R.drawable.moon9,
        R.drawable.moon10,
        R.drawable.moon11,
        R.drawable.moon12,
        R.drawable.moon13,
        R.drawable.moon14,
        R.drawable.moon15,
        R.drawable.moon16,
        R.drawable.moon17,
        R.drawable.moon18,
        R.drawable.moon19,
        R.drawable.moon20,
        R.drawable.travel1,
        R.drawable.travel2,
        R.drawable.travel3,
        R.drawable.travel4,
        R.drawable.travel5,
        R.drawable.travel6,
        R.drawable.travel7,
        R.drawable.travel8,
        R.drawable.travel9,
        R.drawable.travel10,
        R.drawable.travel11,
        R.drawable.travel12,
        R.drawable.travel13,
        R.drawable.travel14,
        R.drawable.travel15,
        R.drawable.travel16,
        R.drawable.travel17,
        R.drawable.travel18,
        R.drawable.travel19,
        R.drawable.travel20,
        R.drawable.love5,
        R.drawable.night10,
        R.drawable.night11,
        R.drawable.night12,
        R.drawable.night13,
        R.drawable.night14,

        R.drawable.love9,
        R.drawable.love10,
        R.drawable.love11,
        R.drawable.love12,
        R.drawable.love13,
        R.drawable.love14,
        R.drawable.bw5,
        R.drawable.bw6,
        R.drawable.bw7,
        R.drawable.bw8,
        R.drawable.bw9,
        R.drawable.bw10,
        R.drawable.bw11,
        R.drawable.bw12,
        R.drawable.bw13,
        R.drawable.bw14,
        R.drawable.bw15,
        R.drawable.bw16,
        R.drawable.bw17,
        R.drawable.bw18,
        R.drawable.bw19,
        R.drawable.bw20,

        R.drawable.sun1,
        R.drawable.sun2,
        R.drawable.sun3,
        R.drawable.sun4,
        R.drawable.sun5,
        R.drawable.sun6,
        R.drawable.sun7,
        R.drawable.sun8,
        R.drawable.sun9,
        R.drawable.sun10,
        R.drawable.sun11,
        R.drawable.sun12,
        R.drawable.sun13,
        R.drawable.sun14,
        R.drawable.sun15,
        R.drawable.sun16,
        R.drawable.sun17,
        R.drawable.sun18,
        R.drawable.sun19,
        R.drawable.sun20,

        R.drawable.anime1,
        R.drawable.anime2,
        R.drawable.anime3,
        R.drawable.anime4,
        R.drawable.anime5,
        R.drawable.anime6,
        R.drawable.anime7,
        R.drawable.anime8,
        R.drawable.anime9,
        R.drawable.anime10,
        R.drawable.anime11,
        R.drawable.anime12,
        R.drawable.anime13,
        R.drawable.anime14,
        R.drawable.anime15,
        R.drawable.anime16,
        R.drawable.anime17,
        R.drawable.anime18,
        R.drawable.anime19,
        R.drawable.anime20,

        R.drawable.classic1,
        R.drawable.classic2,
        R.drawable.classic3,
        R.drawable.classic4,
        R.drawable.classic5,
        R.drawable.classic6,
        R.drawable.classic7,
        R.drawable.classic8,
        R.drawable.classic9,
        R.drawable.classic10,
        R.drawable.classic11,
        R.drawable.classic12,
        R.drawable.classic13,
        R.drawable.classic14,
        R.drawable.classic15,
        R.drawable.classic16,
        R.drawable.classic17,
        R.drawable.classic18,
        R.drawable.classic19,
        R.drawable.classic20,

        R.drawable.flower1,
        R.drawable.flower2,
        R.drawable.flower3,
        R.drawable.flower4,
        R.drawable.flower5,
        R.drawable.flower6,
        R.drawable.flower7,
        R.drawable.flower8,
        R.drawable.flower9,
        R.drawable.flower10,
        R.drawable.flower11,
        R.drawable.flower12,
        R.drawable.flower13,
        R.drawable.flower14,
        R.drawable.flower15,
        R.drawable.flower16,
        R.drawable.flower17,
        R.drawable.flower18,
        R.drawable.flower19,
        R.drawable.flower20,

        )

}




